### ISSUE TITLE
ioservice methods

### ISSUE THREAD

**Issue by nicolaeabacioaiei** [AndoniAndrei/VendingMachine#3]
https://github.com/AndoniAndrei/VendingMachine/blob/dc68158bb7c209c94f92aafce773ef8207fea395/src/main/java/service/IOService.java#L14

clasa asta ar trebui sa aiba metode care se ocupa strict de interactiunea cu utilizatorul
restul logicii de validat, delivery product si pay rest ar trebui sa fie in vending machine

**Comment by AndoniAndrei** [comment]
Tot ma chinui la asta de ceva vreme, dar ii dau de capat! Revin cu rezultate.
